--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Endermanbugzjfc/UselessAPI
build-by-default: true
branches:
- master
projects:
  UselessAPI:
    path: ""
    model: virion
    type: library
...
